### ISSUE TITLE
Rotate Pad

### ISSUE THREAD

**Issue by MathiasSJacobsen** [inf112-v20/error_brain_not_found#105]
Rotate pad working

User-story:
As a user I want to get turned if I walk on a rotate pad

Acceptance-criteria:
* when I move to a tile with a rotated I want to be turned in the direction of the rotate pad

Tasks: 
- [x] make a method that tells if player i on rotate pad and then rotate player 
- [x] test that player is rotated in correct direction

**Comment by MathiasSJacobsen** [comment]
@JennStro Da er den ferdig laget

**Comment by MathiasSJacobsen** [comment]
Testen lager vel du?

**Comment by JennStro** [comment]
Jepp! 😁
