### ISSUE TITLE
Game sometimes crashes after clicking on start menu

### ISSUE THREAD

**Issue by JennStro** [inf112-v20/error_brain_not_found#147]
and getting this error: 

AL lib: (WW) FreeDevice: (0x10d5af000) Deleting 3 Buffer(s) 

Når jeg valgte et brett kom denne mld: 

`
 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007fff424633fc, pid=3169, tid=67591

 JRE version: OpenJDK Runtime Environment (11.0.5+10) (build 11.0.5+10-b520.30)
 Java VM: OpenJDK 64-Bit Server VM (11.0.5+10-b520.30, mixed mode, tiered, compressed oops, g1 gc, bsd-amd64)
 Problematic frame:
C  [GLEngine+0x1473fc]  gleRunVertexSubmitImmediate+0x130c

 No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

 An error report file with more information is saved as:
/Users/Jenny/Desktop/Skole/INF112Oppgave/error_brain_not_found/hs_err_pid3169.log

 If you would like to submit a bug report, please visit:
146  http://bugreport.java.com/bugreport/crash.jsp
The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)`

**Comment by MathiasSJacobsen** [comment]
@JennStro Husker du hvilket brett?

**Comment by JennStro** [comment]
Hm nei, for det kræsjer når man trykker på det bildet som kommer før valgmenyen. Men av og til virker det og da kan jeg velge brett uten problem og det virker. Usikker på om det har noe med mine instillinger å gjøre eller hva. Får uansett den AL lib: (WW) FreeDevice: (0x10d5af000) Deleting 3 Buffer(s) i console etter jeg har kjørt programmet.  

Kan det ha noe med dispose å gjøre? Leste om det her https://stackoverflow.com/questions/22934822/deleting-buffers-libgdx men aner ikke altsp

**Comment by DuyBoi** [comment]
Tror koden er lagt opp til at man kan trykke på knappene i MenuScreen mens man er på LoadingScreen klassen. Har aldri fått den feil meldingen da.

**Comment by DuyBoi** [comment]
Kan egentlig fjerne loadingScreen screenen slik at MenuScreen booter opp med en gang

**Comment by JennStro** [comment]
Så fikk jeg den lange meldingen en gang jeg valgte et brett, husker ikke hvilket, men tror det var fordi jeg av en eller annen grunn hadde JDK 11 og ikke 8. Har byttet til 8 nå, men får fortsatt at den deleter buffrene.

**Comment by JennStro** [comment]
Det virker egentlig som at den bare hopper over hele menyen, og at den av og til bare kræsjer. Kan det ha noe med versjoner av java å gjøre? bruker versjon 8

**Comment by JennStro** [comment]
Ok da har jeg prøvd meg litt frem. Ser ut som det skjer noe i overgangen mellom loadingScreen og menuScreen. Når jeg bytter til at menuscreen vises direkte i game: 

`public void create() {
        this.setScreen(new MenuScreen(this));
        startMusic();
    }`

så funker alt fint =P

@DuyBoi  ser du hva som kan gå galt mellom loadingscreen og menuscreen?

**Comment by DuyBoi** [comment]
Vet ikke hva som kan gå galt, men det er vell ikke et OSx problem? Får du det problemet @MathiasSJacobsen ?
