### ISSUE TITLE
Push player through wall

### ISSUE THREAD

**Issue by MagnusTonnessen** [inf112-v20/error_brain_not_found#148]
Not possible to push 1 player through wall, but when pushing 2 players the one closest to the wall will be pushed through

**Comment by JennStro** [comment]
Laget en test for det nå og det viser grønt. Men kan være noe jeg har misforstått sånn at testen blir feil? Testen:
 
    **public void wallStopsPushingSeveralPlayersTest() {
        // Found wall in Risky Exhange
        Vector2 northWallPosition = new Vector2(0, 5);
        Vector2 middlePosition = new Vector2(0, 4);
        Player playerToBeStoppedByWall = new Player(northWallPosition, 2);
        Player playerInMiddle = new Player(middlePosition, 3);
        playerToBeStoppedByWall.setDirection(Direction.WEST);
        playerInMiddle.setDirection(Direction.SOUTH);
        Vector2 playerPushingPosition = new Vector2(0,3);
        player.setPosition(playerPushingPosition);
        player.setDirection(Direction.NORTH);
        board.addPlayer(playerToBeStoppedByWall);
        board.addPlayer(playerInMiddle);
        board.addPlayer(player);
        board.movePlayer(player);
        assertEquals(playerToBeStoppedByWall, board.getPlayer(northWallPosition));
    }**
